name: Storybook PR Checks
on:
  pull_request:
    branches:
      - master

jobs:
  smartui-gihub-action:
    name: Execute Storybook build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Find Last CommitId
      run: |
        API_HOST=https://api.github.com
        # Check out the PR branch
        git checkout $GITHUB_HEAD_REF
        # Get the commit ID of the last commit
        COMMIT_ID=$(git rev-parse HEAD)
        echo "Last commit ID of PR: $COMMIT_ID"
        GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
        echo "GITHUB_URL: $GITHUB_URL"
        echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV
   
    - name: Install Dependencies
      run: |
        npm install
        npm install @lambdatest/smartui-storybook -g

    - name: Execute storybook build1
      run: |
        export PROJECT_TOKEN=1868537#577319d5-dc00-4045-9748-d1edc1a1c436#telus_prod_dev
        smartui --version
        smartui storybook ./dashlane --config .smartui.json

    - name: Execute storybook build2
      run: |
        export PROJECT_TOKEN=1868537#b0e62662-6dfb-467c-949c-5ef4f887256f#telus_prod_dev_2
        smartui --version
        smartui storybook ./18c18586-e375-4f83-b871-4bfec453c5ef --config .smartui.json