name: Storybook PR Checks

on:
  pull_request:
    branches:
      - master

env:
  PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }} 

jobs:
  smartui-github-action:
    name: Execute Storybook build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Listing directory after step 1
      run: | 
        ls -la

    - name: Check out repo smartui-storybook
      uses: actions/checkout@v1
      with:
        repository: Lambdatest/smartui-storybook
        ref: stage
        path: ss


    - name: Checkout stage branch of the private repo
      run: |
        ls -la
        cd ss
        ls -la
        cd smartui-storybook
        ls -la


    - name: Find Last CommitId
      run: |
        API_HOST=https://api.github.com
        # Check out the PR branch
        git checkout $GITHUB_HEAD_REF
        # Get the commit ID of the last commit
        COMMIT_ID=$(git rev-parse HEAD)
        echo "Last commit ID of PR: $COMMIT_ID"
        GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
        echo "GITHUB_URL: $GITHUB_URL"
        echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV
   
    - name: Install Dependencies
      run: npm install

    - name: Create storybook static build
      run: npm run build-storybook

    - name: Execute storybook build
      run: |
        ls -la
        node ./../smartui-storybook/index.js --version
        node ./../smartui-storybook/index.js config create .smartui.json
        node ./../smartui-storybook/index.js storybook ./18c18586-e375-4f83-b871-4bfec453c5ef --config .smartui.json --env stage
