name: Storybook PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  smartui-github-action:
    name: Execute Storybook build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all branches and tags

    - name: Listing directory after step 1
      run: | 
        ls -la

    - name: Check out repo smartui-storybook
      uses: actions/checkout@v2
      with:
        repository: Lambdatest/smartui-storybook
        ref: stage
        path: ss
        fetch-depth: 0  # Fetch all branches and tags

    - name: Listing directory after checking out smartui-storybook
      run: |
        ls -la
        cd ss
        ls -la

    - name: Step for push event
      run: |
        echo "This is a push event!"
        echo "The latest commitId $(git log -1 --format='%H')"
        echo "COMMIT_ID=$(git log -1 --format='%H')" >> $GITHUB_ENV
      if: github.event_name == 'push'

    - name: Step for pull_request event
      run: |
        echo "This is a pull_request event!"
        git log -n 5 --format="%H %an %s" | while read line; do echo "$line"; done
        echo "The latest commitId $(git log -2 --format='%H' | tail -n 1)"
        echo "COMMIT_ID=$(git log -2 --format='%H' | tail -n 1)" >> $GITHUB_ENV
      if: github.event_name == 'pull_request'

    - name: Step for Publish/Release event
      run: |
        echo "This is a release event!" 
        echo "The latest commitId $(git log -1 --format='%H')"
        echo "COMMIT_ID=$(git log -1 --format='%H')" >> $GITHUB_ENV
      if: github.event_name == 'release'

    - name: Create Github URL1
      run: |
        API_HOST=https://api.github.com
        echo "The latest commitId is $COMMIT_ID"
        GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
        echo "GITHUB_URL: $GITHUB_URL"
   
    - name: Install Dependencies
      run: npm install

    - name: Create storybook static build
      run: npm run build-storybook

    - name: Execute storybook build
      run: |
        ls -la
        node ./ss/index.js --version
        export PROJECT_TOKEN=33416373#2bc23634-a798-4e6a-8e6a-f826cb8b6084#ci_testing
        node ./ss/index.js config create .smartui.json
        node ./ss/index.js storybook ./storybook-static --config .smartui.json --env stage
 