name: Storybook PR Checks
on:
  pull_request:
    branches:
      - master

jobs:
  smartui-gihub-action:
    name: Execute Storybook build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Find Last CommitId
      run: |
        API_HOST=https://api.github.com
        # Check out the PR branch
        git checkout $GITHUB_HEAD_REF
        # Get the commit ID of the last commit
        COMMIT_ID=$(git rev-parse HEAD)
        echo "Last commit ID of PR: $COMMIT_ID"
        GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
        echo "GITHUB_URL: $GITHUB_URL"
        echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV
   
    - name: Install Dependencies
      run: |
        npm install
        npm install @lambdatest/smartui-storybook -g

    - name: Execute storybook build1
      run: |
        export PROJECT_TOKEN=33416373#4e43a26c-35f1-415c-b09d-f8c9820d13f7#dashlane_more_Ci
        smartui --version
        smartui storybook ./dashlane --config .smartui.json --env stage

    - name: Execute storybook build2
      run: |
        export PROJECT_TOKEN=33416373#46d5d595-d3e1-49d2-b37a-d86e9f233a24#storybook_static_ci_test
        smartui --version
        smartui storybook ./dashlane --config .smartui.json --env stage 